loadTimeData.data = {
  bestScore: "最佳 $1 $2 $3",
  bestScoreFlyout: "最佳分数: $1",
  bestScoreMenuDisplay: "$1 $2",
  cancel: "取消",
  close: "关闭",
  code: "已激活作弊代码!",
  codeCheat: "已激活作弊代码! $1",
  codeScoring: "此轮计分已关闭。",
  endlessBestScore: -1,
  endlessDescriptor: "距离",
  endlessModeTitleInline: "无尽模式:",
  endlessTitle: "无尽模式",
  endlessUnit: "米",
  fontfamily: "system-ui, sans-serif",
  fontsize: "75%",
  gameCreditsButton: "游戏制作人员",
  gameCreditsDialogTitle: "游戏制作人员",
  gameMode: "游戏模式改变为 $1",
  gameModeSelectLabel: "游戏模式",
  gameModeSelectLabelDisabled: "游戏模式 (重启游戏以更改模式)",
  gameSettings: "游戏设置",
  highVisibilityActive: false,
  highVisiblityModeToggleLabel: "高可见度",
  howToPlayButton: "玩法",
  howToPlayControllerBoost: "按 'RT' 以使用速度提升",
  howToPlayControllerMovement: "使用操纵杆或方向键来控制方向",
  howToPlayControllerRefresh: "按 LB+RB 重启游戏",
  howToPlayDialogTitle: "玩法",
  howToPlayEndless:
    "尽量向前走并救助好友来帮忙对付敌人",
  howToPlayKeyboardBoost: "按 'F' 以使用速度提升",
  howToPlayKeyboardMovement: "使用箭头或 'WASD' 键来控制方向",
  howToPlayKeyboardRefresh: "刷新页面以重启游戏",
  howToPlayMouseBoost: "右键以使用速度提升",
  howToPlayMouseMovement: "移动鼠标以控制方向",
  howToPlayMouseRefresh: "刷新页面以重启游戏",
  howToPlayTimeTrial:
    "尽快到达终点并收集硬币以减少时间",
  howToPlayTouchBoost: "向下轻扫两次即可使用速度提升",
  howToPlayTouchMovement: "轻扫或点击以控制方向",
  howToPlayTouchRefresh: "刷新页面以重启游戏",
  howToPlayZigZag: "连续通过尽可能多的关口",
  is_windows_xbox_sku: "false",
  keyboardAction: "空格键",
  language: "en",
  lastSelectedMode: "endless",
  lastSelectedPlayer: 4,
  lastSelectedTheme: "surf",
  menuInfo: "开始玩游戏",
  mouseAction: "双击",
  newBestScore: "新的最佳 $1 $2 $3",
  newGame: "开始新游戏",
  off: "关",
  on: "开",
  overInfo: "再玩一次",
  overTitle: "",
  pauseInfo: "继续游戏",
  pauseTitle: "游戏暂停",
  reducedSpeedActive: false,
  reducedSpeedModeToggleLabel: "降低速度",
  resetAllStats: "重置所有统计信息",
  resetAllStatsDialogText:
    "是否确实要重置所有游戏统计信息(包括高分)?",
  resetAllStatsDialogTitle: "重置所有统计信息",
  share: "与好友共享",
  shareCopy: "复制",
  shareLink: "https://littlegaofx.github.io/Surf/",
  shareLinkCopied: "已复制!",
  skiTheme: "让我们滑雪",
  specialThanks: "特别感谢:",
  surfTheme: "让我们网上冲浪吧",
  textdirection: "ltr",
  theme: "游戏主题更改为 $1",
  themeSelectLabel: "主题",
  timetrialBestScore: -1,
  timetrialDescriptor: "time",
  timetrialModeTitleInline: "计时赛:",
  timetrialTitle: "计时赛",
  timetrialUnit: "秒",
  touchAction: "双击",
  zigzagBestScore: -1,
  zigzagDescriptor: "streak",
  zigzagModeTitleInline: "障碍赛:",
  zigzagTitle: "障碍赛",
  zigzagUnit: "关口",
  other: "其它",
};
